### ISSUE TITLE
Crash on attempt to download

### ISSUE THREAD

**Issue by Wohlstand** [Luigifan/LuaScriptsManager#1]
Crash happened on Linux Mint 17.2, when I answered 'yes' to "Do you wanna download update?". I saw the progress dialog, but got a crash

``` text
vitaly@WHL-PC-001L ~/.PlayOnLinux/wineprefix/smbxlua/drive_c/LuaModuleManager $ mono ./LuaModuleManager.exeSettings found in "/home/vitaly/.luamodulemanager"
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style, IFormatProvider provider) [0x00000] in <filename unknown>:0 
  at System.Double.Parse (System.String s) [0x00000] in <filename unknown>:0 
  at System.Convert.ToDouble (System.String value) [0x00000] in <filename unknown>:0 
  at Gtktester.Downloader+<>c__DisplayClass5.<BeginDownload>b__2 (System.Object param0, System.EventArgs param1) [0x00000] in <filename unknown>:0 
  at Gtk.Application+InvokeCB.Invoke () [0x00000] in <filename unknown>:0 
  at GLib.Timeout+TimeoutProxy.Handler () [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.Timeout+TimeoutProxy.Handler()
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run()
   at Gtktester.Program.Main(System.String[] args)
vitaly@WHL-PC-001L ~/.PlayOnLinux/wineprefix/smbxlua/drive_c/LuaModuleManager $ 
```

**Comment by suicvne** [comment]
Fixed in 5643b529ada5c480dddfb742f36ec34431e7c401 :)
